name = "After The End"
author = "klukva008, Prismista, metan, primista"
version = "dev0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ee979ba83ae5a8a05e662222a71d636a6d593b90642461b4eb646479d425048"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = []
