name = "After The End"
author = "klukva008, Prismista, metan, primista"
version = "dev0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ffe15cecdadad9f0e812482a2fc83d0a5602cc21de5fe849522d50d4a851c46"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = []
