name = "After The End"
author = "klukva008, Prismista, metan, primista"
version = "dev0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07bdd116d36459a9a0a403acf56ff7fa1281897b1a00888e325811b58c1121bb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = []
